name: Build WAR

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Maven
        run: |
          mvn -version

      - name: Build WAR using Maven
        run: |
          mvn clean package

      - name: Copy WAR to Server
        run: |
          sshpass -p v1e1n1k1  scp -o StrictHostKeyChecking=no target/myapp-v1.war ceadmin@192.168.116.128:/home/ceadmin/
